name: build_vim

on:
  push:
    tags:
      - vim_debian_9_12_*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        cd docker/build_vim_debian_9_12
        make

    - uses: actions/upload-artifact@v1
      with:
        name: vim_debian_9_12
        path: docker/build_vim_debian_9_12/package.tar.gz
